# Generated by Django 2.2.3 on 2019-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='goods/', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='goods/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='type/', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='url',
            field=models.CharField(max_length=256, verbose_name='活动链接'),
        ),
    ]
